### ISSUE TITLE
incorrect validation of numbers

### ISSUE THREAD

**Issue by petrosagg** [g0d/Vulcan#1]
The library incorrectly thinks that an empty array is a number

```javascript
var my_vulcan = new vulcan();
var arr = []
console.log(my_vulcan.validation.numerics.is_number(arr))
```

**Comment by abresas** [comment]
the function is meant to be used only with numeric inputs, of course.

**Comment by petrosagg** [comment]
@abresas how do I verify if the input is numeric before I pass it to this function?

**Comment by abresas** [comment]
the function checks if the value *can* be coerced into a number, as per the ecmascript 5.1 language specification https://www.ecma-international.org/ecma-262/5.1/#sec-15.1.2.4

**Comment by g0d** [comment]
Hello fellow engineers and thanks for the comments.
Please make sure you check all my work ONLY under the miro-MVC project. I am not maintaining any libraries independently. This Vulcan is an old one for example. I will delete all extra repos.
So, for you to help me out please revalidate this: https://github.com/g0d/micro-MVC/blob/master/framework/extensions/js/vulcan/vulcan.js

I will check your comments and come back with a fix. @petrosagg, you are right. This needs to be more strict. I will fix that for sure!.

Keep up the good work and please make sure you check everything only under https://github.com/g0d/micro-MVC/ from now on!

**Comment by g0d** [comment]
Fix has been applied at: https://github.com/g0d/micro-MVC/blob/master/framework/extensions/js/vulcan/vulcan.js

Thanks a lot all of you!
