### ISSUE TITLE
incorrect validation of floats

### ISSUE THREAD

**Issue by petrosagg** [g0d/Vulcan#2]
The library incorrectly thinks that 0 is a float

```javascript
var my_vulcan = new vulcan();
console.log(my_vulcan.validation.numerics.is_float(0))
```

**Comment by abresas** [comment]
For your information, 

> JavaScript numbers are always stored as double precision floating point numbers

https://www.w3schools.com/js/js_numbers.asp

Therefore, 0 is also a float in javascript.

**Comment by g0d** [comment]
@petrosagg , 0 is a valid float. It is correct. All numbers in JS are floats. Hence my check in the: is_integer function where I do:
`if (__self.is_number(val) && (val % 1 === 0) && !self.misc.contains('.', val.toString()))
                    return true;

 return false;`

**Comment by g0d** [comment]
This is not an issue. I am closing this. Thanks for your comments and please remember that my most recent work lies under https://github.com/g0d/micro-MVC/
